"""empty message

Revision ID: 39f7913387f8
Revises: 
Create Date: 2021-05-24 16:57:27.751142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f7913387f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_table',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=20), nullable=False),
    sa.Column('student_age', sa.Integer(), nullable=False),
    sa.Column('student_section', sa.String(length=6), nullable=False),
    sa.Column('student_gender', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_table')
    # ### end Alembic commands ###
